In [1]:
from utils import data

In [5]:
df = data.load_analysis_columns(["cluster_id", "cluster_size"], resolution=0.3)

In [9]:
df.head()

shape: (5, 6)
┌──────────────┬──────────────────┬────────────┬──────────────────┬─────────────────┬──────────────┐
│ cluster_size ┆ collection_date  ┆ resolution ┆ sequence_id      ┆ cluster_id      ┆ nextclade_qc │
│ ---          ┆ ---              ┆ ---        ┆ ---              ┆ ---             ┆ ---          │
│ i64          ┆ datetime[ns]     ┆ f64        ┆ str              ┆ str             ┆ str          │
╞══════════════╪══════════════════╪════════════╪══════════════════╪═════════════════╪══════════════╡
│ 1            ┆ 2020-07-04       ┆ 0.3        ┆ Scotland/CVR3946 ┆ W001|B.1.1.369| ┆ good         │
│              ┆ 00:00:00         ┆            ┆ /2020            ┆ R0.3|S1         ┆              │
│ 3            ┆ 2020-07-13       ┆ 0.3        ┆ Scotland/CVR3956 ┆ W002|B.1.1.369| ┆ good         │
│              ┆ 00:00:00         ┆            ┆ /2020            ┆ R0.3|C2         ┆              │
│ 3            ┆ 2020-07-13       ┆ 0.3        ┆ Scotland/CVR3956 ┆ W001|B.1.1.369| ┆ good         │
│              ┆ 00:00:00         ┆            ┆ /2020            ┆ R0.3|C2         ┆              │
│ 1            ┆ 2020-07-13       ┆ 0.3        ┆ Scotland/QEUH-94 ┆ W001|B.1.1.10|R ┆ good         │
│              ┆ 00:00:00         ┆            ┆ 384C/2020        ┆ 0.3|S0          ┆              │
│ 1            ┆ 2020-07-13       ┆ 0.3        ┆ Scotland/QEUH-94 ┆ W002|B.1.1.10|R ┆ good         │
│              ┆ 00:00:00         ┆            ┆ 384C/2020        ┆ 0.3|S0          ┆              │
└──────────────┴──────────────────┴────────────┴──────────────────┴─────────────────┴──────────────┘

In [6]:
df.shape

(789347, 6)

In [7]:
df["sequence_id"].n_unique(), df["cluster_id"].n_unique()

(281320, 193160)

In [8]:
df["cluster_size"].describe(percentiles=[0.95])

shape: (7, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 789347.0   │
│ null_count ┆ 0.0        │
│ mean       ┆ 198.774422 │
│ std        ┆ 479.787407 │
│ min        ┆ 1.0        │
│ 95%        ┆ 1283.0     │
│ max        ┆ 3241.0     │
└────────────┴────────────┘