In [1]:
import pandas as pd

In [2]:
class DOMAINS:
    overall: str = "dz_simd_rank"
    income: str = "dz_simd_income_rank"
    employment: str = "dz_simd_employment_rank"
    education: str = "dz_simd_education_rank"
    health: str = "dz_simd_health_rank"
    access: str = "dz_simd_access_rank"
    crime: str = "dz_simd_crime_rank"
    housing: str = "dz_simd_housing_rank"

df = pd.read_parquet(
    "../data/processed/scotland_clustering_analysis_dataset.parquet",
    columns=[
        "sequence_id", "collection_date", "who_voc",
        "datazone", "dz_simd_rank", "dz_simd_income_rank",
        "dz_simd_employment_rank", "dz_simd_education_rank", "dz_simd_health_rank",
        "dz_simd_access_rank", "dz_simd_crime_rank", "dz_simd_housing_rank"
    ]
)

In [3]:
df.drop_duplicates(inplace=True, subset=["sequence_id"])
df.sort_values("collection_date", ascending=True, inplace=True)
who_voc = df.drop_duplicates(subset=["who_voc"], keep="first")
datazone = df.drop_duplicates(subset=["datazone"], keep="first")

In [5]:
datazone[[
    "dz_simd_income_rank", "dz_simd_employment_rank", "dz_simd_education_rank",
    "dz_simd_health_rank", "dz_simd_access_rank", "dz_simd_crime_rank", "dz_simd_housing_rank"
]].corr()

,dz_simd_income_rank,dz_simd_employment_rank,dz_simd_education_rank,dz_simd_health_rank,dz_simd_access_rank,dz_simd_crime_rank,dz_simd_housing_rank
dz_simd_income_rank,1.000000,0.963877,0.885512,0.940527,-0.344028,0.642822,0.698732
dz_simd_employment_rank,0.963877,1.000000,0.861753,0.941805,-0.336398,0.636160,0.658808
dz_simd_education_rank,0.885512,0.861753,1.000000,0.855984,-0.273684,0.600759,0.681887
dz_simd_health_rank,0.940527,0.941805,0.855984,1.000000,-0.350256,0.621240,0.650618
dz_simd_access_rank,-0.344028,-0.336398,-0.273684,-0.350256,1.000000,-0.441486,-0.429453
dz_simd_crime_rank,0.642822,0.636160,0.600759,0.621240,-0.441486,1.000000,0.591279
dz_simd_housing_rank,0.698732,0.658808,0.681887,0.650618,-0.429453,0.591279,1.000000

In [14]:
df.shape

(324194, 3)

In [13]:
who_voc

                        sequence_id collection_date      who_voc
8             Scotland/CVR3946/2020      2020-07-04         None
151968    Scotland/QEUH-B3184F/2020      2020-11-04        Alpha
201048    Scotland/QEUH-F389E7/2020      2020-12-16         Beta
240552       Scotland/EDB16145/2021      2021-01-20          Eta
274528       Scotland/EDB14957/2021      2021-02-04        Gamma
7375000      Scotland/CVR14236/2021      2021-02-20      Omicron
458064   Scotland/CAMC-139C20D/2021      2021-03-06        Kappa
7375328       Scotland/CVR8092/2021      2021-04-02        Delta
1543712      Scotland/EDB20741/2021      2021-07-28        Theta
1687024  Scotland/MILK-1B59E00/2021      2021-08-07           Mu
7379088  Scotland/QEUH-326B68E/2022      2022-01-13  recombinant

In [8]:
df["who_voc"].value_counts().keys()

Index(['Omicron', 'Delta', 'Alpha', 'recombinant', 'Beta', 'Eta', 'Kappa',
       'Gamma', 'Theta', 'Mu'],
      dtype='object', name='who_voc')

In [22]:
df["collection_date"].min(), df["collection_date"].max()

(Timestamp('2020-07-04 00:00:00'), Timestamp('2023-02-10 00:00:00'))